### ISSUE TITLE
Chat Autoclearing on 1.6.0

### ISSUE THREAD

**Issue by djdeadllama** [jonagamerpro1234/AdvancedChat#11]
I have it set to false, and its still autocleaning the chat. I tried changing the time to -1, and 9999999999 to see if it had any effect. All the same results: autoclean. I switched back to 1.5.9 and the autoclean works properly. Paper 1.17.1 (Build 399)

**Comment by jonagamerpro1234** [comment]
I need you to provide me your config.yml to give you better help
