### ISSUE TITLE
[Feature request]

### ISSUE THREAD

**Issue by LiamiP-7** [jonagamerpro1234/AdvancedChat#17]
could you add a option that you can customize the prefix of the message that is sent in console chat becouse it looks very weird 
![fixthiss](https://user-images.githubusercontent.com/96143260/168769943-6e7aafb3-e2d1-48a7-8131-609db3e7b807.png)

**Comment by jonagamerpro1234** [comment]
yes no problem and thanks for the suggestion

This may take a while because I'm changing all the code
