### ISSUE TITLE
Harmful pronoun usage

### ISSUE THREAD

**Issue by Avedia1** [jonagamerpro1234/AdvancedChat#6]
![image](https://user-images.githubusercontent.com/92314446/136796240-567ceeaf-8172-412e-a93a-27422e06d91b.png)
I came across this in your AdvancedChat plugin for 1.17
I am transgender male to female so seeing this causes me quite a bit of gender dysphoria.
If you will, could you please change it to "they are" instead of "he is"?
Thanks!

**Comment by jonagamerpro1234** [comment]
no problem, it will be modified for the next update
